# Generated by Django 4.2.2 on 2023-08-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imob', models.IntegerField()),
                ('local', models.TextField()),
                ('setor', models.TextField()),
                ('responsavel', models.TextField()),
                ('tipo', models.TextField()),
                ('modelo', models.TextField()),
                ('win', models.TextField()),
                ('chave_win', models.TextField(blank=True, null=True)),
                ('mac', models.TextField()),
                ('mac_wifi', models.TextField()),
                ('office', models.TextField()),
                ('chave_office', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('acesso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manutencoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imob', models.CharField(max_length=30)),
                ('data_manutencao', models.TextField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tecnico_responsavel', models.TextField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ativos')),
            ],
        ),
    ]
